version: 0.2.3.{build}

configuration: Release

before_build:
    - dotnet restore .\src

build_script:
    - dotnet build .\src\Amazon.SQS.ExtendedClient.sln

test_script:
    - dotnet test .\src\Amazon.SQS.ExtendedClient.Tests\Amazon.SQS.ExtendedClient.Tests.csproj

branches:
    only:
        - master
